/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import io.lettuce.core.RedisClient;
import java.util.concurrent.TimeoutException;
import java.util.Map;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.rabbitmq.client.Channel;
import com.rabbitmq.client.Connection;
import com.rabbitmq.client.ConnectionFactory;
import com.rabbitmq.client.DeliverCallback;
import io.lettuce.core.api.StatefulRedisConnection;

public class App {

    //mysql 관련 변수
    static String DB_URL;
    static String DB_USER;
    static String DB_PASSWORD;

    //redis 관련 변수
    static RedisClient redisClient;
    static StatefulRedisConnection<String, String> redisConnection;

    public static void main(String[] args) {

        Init init = new Init();
        RabbitmqUtility ru = new RabbitmqUtility();

        // 초기화 작업 .....
        // 1) 환경 변수 설정하기 (DB_URL, DB_USER, DB_PASSWORD 초기화)
        init.setProperties();

        // 2) redis 에 연결
        init.connectRedis();

        //현재 경로 확인용
        //System.out.println("Working Directory = " + System.getProperty("user.dir"));

        // 3) rabbitmq 에 접속한다. spring.education.queue 에 메세지가 들어오면 ru.createDeliverCallback() 에 해당하는 DeliverCallback 이 실행된다
        try{
            ConnectionFactory factory = new ConnectionFactory();
            factory.setHost("localhost");
            Connection connection = factory.newConnection();
            Channel channel = connection.createChannel();

            channel.queueDeclare("spring.education.queue", true, false, false, null);
            System.out.println(" [*] Waiting for messages. To exit press CTRL+C");

            channel.basicConsume("spring.education.queue", true, ru.createDeliverCallback(), consumerTag -> { });
        }catch(IOException e){
            e.printStackTrace();
        }catch(TimeoutException e){
            e.printStackTrace();
        }
    }
}
